server:
  port: 9005
spring:
  application:
    name: coin-wallet
  rabbitmq:
      host: 172.31.4.104
      port: 5672
      username: adminw
      password: admin345
  redis:
      host: 172.31.4.104
      port: 7865
      password: LnK#@UioRT2
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://172.31.4.104:3306/coin_wallet?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
      username: root
      password: BAMCDX123.
      type: com.alibaba.druid.pool.DruidDataSource
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
mybatis:
   config-location: classpath:mybatis-config.xml
   mapper-locations: classpath*:com/coinwallet/**/mapper/*.xml # mapper文件扫描



