server:
  port: 9005
spring:
  application:
    name: coin-wallet
  rabbitmq:
      host: 139.129.246.185
      port: 5672
      username: hanhaigang
      password: pUC9jyg7auNVAD
  redis:
      host: 139.129.246.185
      port: 6379
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://139.129.246.185:3306/coin_wallet?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: bamcdx123.
      type: com.alibaba.druid.pool.DruidDataSource
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
mybatis:
   config-location: classpath:mybatis-config.xml
   mapper-locations: classpath*:com/coinwallet/**/mapper/*.xml # mapper文件扫描



